blogsapp/blogs/urls.py
from django.urls import path

from blogsapp.blogs.views import (
    BlogsView,
    CreateBlogView,
    DetailBlogView,
    UpdateBlogView,
)

app_name = "blog"

urlpatterns = [
    path(
        "",
        BlogsView.as_view(),
        name="homepage_view",
    ),
    path("blogs/new", CreateBlogView.as_view(), name="create_blog_view"),
    path("blogs/update/<str:slug>", UpdateBlogView.as_view(), name="update_blog_view"),
    path("blogs/<str:slug>", DetailBlogView.as_view(), name="blog_detail_view"),
]

blogsapp/users/urls.py
from django.urls import path

from blogsapp.users.views import (
    user_detail_view,
    user_logout_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    path("logout/", view=user_logout_view, name="logout"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("blogsapp.users.urls", namespace="users")),
    path("blogs/", include("blogsapp.blogs.urls", namespace="blogs")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("i18n/", include("django.conf.urls.i18n")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path("", include("blogsapp.blogs.urls")),
    path("", include("blogsapp.users.urls")),
)

if "rosetta" in settings.INSTALLED_APPS:
    urlpatterns += [
        path("rosetta/", include("rosetta.urls")),
    ]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

blogsapp/blogs/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from tinymce.models import HTMLField

from blogsapp.utils.helpers import random_n_token
from blogsapp.utils.managers import BaseObjectManagerQuerySet
from blogsapp.utils.models import BaseModel


class Blog(BaseModel):
    """Blogs model"""

    title = models.CharField(max_length=255)
    slug = models.CharField(max_length=255, blank=True)
    description = HTMLField()
    ta_title = models.CharField(max_length=255)
    ta_description = HTMLField()

    author = models.ForeignKey(
        get_user_model(), related_name="blogs", on_delete=models.CASCADE
    )
    cover_image = models.ImageField(upload_to="blog-images/", blank=True, null=True)

    objects = BaseObjectManagerQuerySet.as_manager()

    class Meta:
        verbose_name = "blog"
        verbose_name_plural = "blogs"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title) + "-" + random_n_token()
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("blog:blog_detail_view", args=[self.slug])

blogsapp/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, PositiveSmallIntegerField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from blogsapp.users.taxonomies import UserRole


class User(AbstractUser):
    """
    Default custom user model for blogsapp.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore
    role = PositiveSmallIntegerField(
        choices=UserRole.choices, default=UserRole.customer
    )

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

    def can_access_admin_panel(self):
        """Check if user can access admin panel."""

        return self.role == UserRole.admin

blogsapp/utils/models.py
import uuid

from django.db import models

from .managers import BaseObjectManagerQuerySet


class BaseModel(models.Model):
    """
    Contains the last modified and the created fields, basically
    the base model for the entire app.
    """

    # unique id field
    id = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)

    # time tracking
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # custom manager
    objects = BaseObjectManagerQuerySet.as_manager()

    class Meta:
        ordering = ["-created_at"]
        abstract = True

blogsapp/blogs/forms.py
from ..utils.forms import AppModelForm
from .models import Blog


class BlogForm(AppModelForm):
    class Meta(AppModelForm.Meta):
        fields = [
            "cover_image",
            "title",
            "description",
            "ta_title",
            "ta_description",
        ]
        model = Blog

    def __init__(self, *args, **kwargs):
        self.author = kwargs.pop("author")
        super().__init__(*args, **kwargs)
        self.fields["cover_image"].label = "Cover Photo"
        self.fields["ta_title"].label = "தலைப்பு"
        self.fields["ta_description"].label = "விளக்கம்"

    def clean_title(self):
        title = self.cleaned_data["title"].strip()
        return title

blogsapp/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

blogsapp/utils/forms.py
from django.forms import Form, ModelForm
from django.forms.forms import BaseForm


class AppBaseForm(BaseForm):
    """
    Base class for the ModelForm and the Form class. This implements some
    common and useful fields and methods. and of course makes things DRY.

    Why is this here?
        1. Without overriding you cannot access the request/view, so helps in validations.
        2. You don't need to do self.cleaned_data['key'], if in case you need to boost performance this is a mess.
    """

    class Meta:
        pass

    def __init__(self, *args, **kwargs):
        """Overridden to get other context data from the view."""

        self.context = kwargs.pop("context", {})
        super().__init__(*args, **kwargs)

    def get_cleaned_data(self, key="__all__", default=None):
        """
        Returns the value from the cleaned data dict based on the given key.
        If in case some other things are to be added, it can be added here.
        This acts as a single point of contact.
        """

        if key == "__all__":
            return self.cleaned_data

        if hasattr(self, "cleaned_data"):
            return self.cleaned_data.get(key, default)

        return self.data.get(key, default)

    def get_user(self):
        """Returns the currently logged in user."""

        request = self.get_request()
        if request:
            return request.user

        return None

    def get_request(self):
        """
        Used as a single point of contact. Just in case the request
        would come from some other ways.
        """

        return self.context.get("request", None)


class AppForm(AppBaseForm, Form):
    """
    The applications normal form. Implements common methods and stuff.

    Consider you are inheriting a form and that form has defined 10 error messages,
    but you want to modify only one error message. You might have to copy all the 10 and
    paste it in the child class.

    This class will reduce this headache. (By default implemented in the ModelForm)

    Note that anything that is defined in the Meta will be higher precedence.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if hasattr(self, "error_messages"):
            # defined in parent class, overridden in child class
            self.error_messages.update(getattr(self.Meta, "custom_error_messages", {}))

    class Meta(AppBaseForm.Meta):
        custom_error_messages = {}


class AppModelForm(AppBaseForm, ModelForm):
    """The applications model form. Implements common methods and stuff."""

    class Meta(AppBaseForm.Meta):
        fields = []
        model = None
        extra_kwargs = {}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, config in self.Meta.extra_kwargs.items():
            for key, value in config.items():
                setattr(self.fields[field_name], key, value)

    def save(self, commit=True):
        """Set necessary hidden fields on save, like created_by."""

        instance = super().save(commit=commit)

        # setting the anonymous fields
        if hasattr(instance, "created_by") and not instance.created_by:
            instance.created_by = self.get_user()
            instance.save()

        return instance


def get_app_model_form(
    given_model, given_fields="__all__", exclude_fields=["created_by"]  # noqa
):
    """
    This function is used to dynamically generate an AppModelForm. Given the set of inputs.
    This is used to dynamically generate forms for the meta tables.
    """

    class _ModelForm(AppModelForm):
        """The dynamic form that is being generated. This is returned as an output."""

        class Meta(AppModelForm.Meta):
            model = given_model
            fields = given_fields
            exclude = exclude_fields

    return _ModelForm

blogsapp/blogs/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse

from blogsapp.blogs.forms import BlogForm
from blogsapp.blogs.models import Blog
from blogsapp.utils.mixins import (
    AppAdminTypeOnlyAllowedMixin,
    AppCreateView,
    AppDetailView,
    AppListView,
    AppLoginRequiredMixin,
    AppUpdateView,
)


class BlogsView(AppLoginRequiredMixin, AppListView):
    template_name = "blogs/homepage.html"
    queryset = Blog.objects.select_related("author").order_by("-updated_at")
    context_object_name = "blogs"


class DetailBlogView(AppLoginRequiredMixin, AppDetailView):
    model = Blog
    queryset = Blog.objects.select_related("author").all()
    template_name = "blogs/blog.html"
    context_object_name = "blog"
    slug_field = "slug"


class CreateBlogView(AppAdminTypeOnlyAllowedMixin, AppCreateView):
    template_name = "blogs/blog_create.html"
    form_class = BlogForm

    def form_valid(self, form):
        """Data is valid, create blog."""

        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return HttpResponseRedirect(
            reverse("blog:blog_detail_view", args=[self.object.slug])
        )

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super().get_form_kwargs()
        kwargs["author"] = self.request.user
        return kwargs


class UpdateBlogView(AppAdminTypeOnlyAllowedMixin, AppUpdateView):
    template_name = "blogs/blog_create.html"
    form_class = BlogForm
    model = Blog
    queryset = Blog.objects.select_related("author").all()
    context_object_name = "blog"
    slug_field = "slug"

    def get_success_url(self):
        return reverse("blog:blog_detail_view", args=(self.object.slug,))

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super().get_form_kwargs()
        kwargs["author"] = self.request.user
        return kwargs

blogsapp/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


class UserLogoutView(LogoutView):
    """View from the user can log out of our application."""

    pass


user_logout_view = UserLogoutView.as_view()

blogsapp/templates/blogs/blog.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{%block title%} Sign Up {%endblock%}

{% block content %}
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'blog:homepage_view' %}">
        <i class="fa-solid fa-arrow-left"></i>
    </a>
    <div class="d-flex">
        {% if request.user.can_access_admin_panel %}
        <a class="navbar-brand btn btn-warning" href="{% url 'blog:update_blog_view' blog.slug %}">
            <i class="fa-solid fa-pen-to-square"></i>
        </a>
        {% endif %}
    </div>
  </div>
</nav>

{% if blog.cover_image %}
    <img src="{{ blog.cover_image.url }}" alt="cover photo" width="100%" height="300">
{% endif %}

{% if lang == 'en' %}

    {{ blog.title|title|safe }}
    <br /><br>
    {{ blog.description|safe }} <br />

{% else %}

    {{ blog.ta_title|title|safe }}
    <br /><br>
    {{ blog.ta_description|safe }} <br />

{% endif %}

<br>
<strong>{% trans "Author" %}</strong> - {{ blog.author.name }} <br />

{% endblock %}

blogsapp/templates/blogs/blog_create.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %} Write Blog {% endblock %}
{% block content %}

<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'blog:homepage_view' %}">
        <i class="fa-solid fa-arrow-left"></i>
    </a>
      {% if blog.slug %}
    <div class="d-flex">
        <a class="navbar-brand btn btn-warning" href="{% url 'blog:blog_detail_view' blog.slug %}">
                <i class="fa-solid fa-eye"></i>
        </a>
    </div>
      {% endif %}
  </div>
</nav>


<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.cover_image|as_crispy_field }}

    <h3>{% trans "English" %}</h3> <br>
    {{ form.title|as_crispy_field }}
    {{ form.description|as_crispy_field }}
    <br>
    <h3>{% trans "Tamil" %}</h3> <br>
    {{ form.ta_title|as_crispy_field }}
    {{ form.ta_description|as_crispy_field }}

    {% include 'includes/form_errors.html' %}

    <button type="submit" class="btn btn-primary">Save</button>
</form>

<script>
    tinyMCE.init({
      selector: "#id_description, #id_ta_description",
    });
</script>

{% endblock %}

blogsapp/templates/blogs/homepage.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{%block title%} Sign Up {%endblock%}

{% block content %}

<table class="table text-center">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">{% trans "Title" %}</th>
      <th scope="col">{% trans "Description" %}</th>
      <th scope="col">{% trans "Author" %}</th>
      <th scope="col" width="20%">{% trans "Actions" %}</th>
    </tr>
  </thead>
  <tbody>
  {% if blogs %}
    {% for blog in blogs %}
    <tr>
        <th>{{ forloop.counter }}</th>
        {% if lang == 'en' %}
            <td>{{ blog.title|title|striptags }}</td>
            <td>{{ blog.description|truncatechars:20|striptags  }}</td>
        {% else %}
            <td>{{ blog.ta_title|striptags }}</td>
            <td>{{ blog.ta_description|truncatechars:20|striptags  }}</td>
        {% endif %}
        <td>{{ blog.author.name }}</td>
        <td>
            <a type="button" class="btn btn-primary" href="{% url 'blog:blog_detail_view' blog.slug %}">
                <i class="fa-solid fa-eye"></i>
            </a>
            {% if request.user.can_access_admin_panel %}
            <a type="button" class="btn btn-warning" href="{% url 'blog:update_blog_view' blog.slug %}">
                <i class="fa-solid fa-pen-to-square"></i>
            </a>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
  {% else %}
  <tr>
    <th colspan="5" class="text-center"> There are no blogs yet </th>
  </tr>
  {% endif %}
  </tbody>
</table>

<div class="row">
    {% for blog in blogs %}
    <div class="col-lg-3">
        <div class="card h-100" style="width: 18rem;">
            {% if blog.cover_image %}
            <img src="{{ blog.cover_image.url }}" class="card-img-top" alt="blog image" style="height: 15rem;">
            {% else %}
            <svg class="bd-placeholder-img card-img-top" width="100%" height="180" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Image cap" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96"></rect></svg>
            {% endif %}
            <div class="card-body">
                {% if lang == 'en' %}
                <h5 class="card-title">{{ blog.title|title|striptags   }}</h5>
                <p class="card-text">{{ blog.description|truncatechars:20|striptags  }}</p>
                {% else %}
                <h5 class="card-title">{{ blog.ta_title|title|safe|escape }}</h5>
                <p class="card-text">{{ blog.ta_description|truncatechars:20|striptags   }}</p>
                {% endif %}
                <p class="card-text"><strong>{% trans "Author" %} - </strong> {{ blog.author.name }}</p>
                <div class="card-footer">
                    <small>
                    <a type="button" class="btn btn-primary"
                       href="{% url 'blog:blog_detail_view' blog.slug %}">
                        <i class="fa-solid fa-eye"></i>
                    </a>
                    {% if request.user.can_access_admin_panel %}
                    <a type="button" class="btn btn-warning"
                       href="{% url 'blog:update_blog_view' blog.slug %}">
                        <i class="fa-solid fa-pen-to-square"></i>
                    </a>
                    {% endif %}
                        </small>
                </div>

            </div>
        </div>
    </div>
    {% endfor %}

</div>


{% endblock %}